export const CONNECT = "CONNECT";
export const DISCONNECT = "DISCONNECT";

export const BROADCAST_MESSAGE = "BROADCAST_MESSAGE";
export const RECEIVE_BROADCAST_MESSAGE = "RECEIVE_BROADCAST_MESSAGE";
export const MESSAGE_ROOM = "MESSAGE_ROOM";
export const RECEIVE_ROOM_MESSAGE = "RECEIVE_ROOM_MESSAGE";
export const MESSAGE_SELF = "MESSAGE_SELF";
export const RECEIVE_SELF_MESSAGE = "RECEIVE_SELF_MESSAGE";
export const JOIN_ROOM = "JOIN_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";

export const CREATE_DRAW = "CREATE_DRAW";
export const UPDATE_DRAW = "UPDATE_DRAW";
export const FINISH_DRAW = "FINISH_DRAW";
export const SELECT_DRAW = "SELECT_DRAW";
export const RECEIVE_UPDATE_DRAW = "RECEIVE_UPDATE_DRAW";
export const RECEIVE_SELECT_DRAW = "RECEIVE_SELECT_DRAW";
